apiVersion: kuadrant.io/v1
kind: RateLimitPolicy
metadata:
  name: echo-api-ratelimit
  namespace: mesh-demo-apps
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: echo-route
  limits:
    "global":
      rates:
        - limit: 5
          window: 10s
